spring.application.name=password-manager

server.port=8080

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=c##revature
spring.datasource.password=rev2354
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# JWT Configuration
jwt.secret=MySuperSecureSecretKeyForRevPasswordManager12345
jwt.expiration=3600000


# Log file name
logging.file.name=logs/password-manager.log

# Log level
logging.level.root=INFO
logging.level.com.revature.pm=DEBUG

# Log pattern
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %level - %logger - %msg%n